### PR TITLE
Add laws for abs and signum

### LINKED ISSUE #110: Missing Num laws for abs and signum
`numLaws` actually misses the only law mentioned in [Haskell Report 2010](https://www.haskell.org/onlinereport/haskell2010/haskellch6.html#x13-1390006.4.4):

```haskell
abs x * signum x == x
``` 

I would also test that 
```haskell
abs (abs x) == abs x 
signum (signum x) == signum x 
```

If we have a consensus on this matter, I can prepare a PR shortly.

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #110.

### CODE REVIEW

**Comment by chessai** [comment]
Danke

**Comment by andrewthad** [comment]
Looks good. Missing an entry in the change log, but I’ll add that when I get back to a computer.

**Comment by Bodigrim** [comment]
@andrewthad @chessai I would appreciate a new release, including this law.

**Comment by Bodigrim** [comment]
This change is mentioned as included in `quickcheck-classes-0.6.4.0`: http://hackage.haskell.org/package/quickcheck-classes-0.6.4.0/changelog 
But this is weird, because it applies to `quickcheck-classes-base` only. Could we possibly have it released at some point?

**Comment by andrewthad** [comment]
The changelog situation is a little weird since `quickcheck-classes` reexports everything from `quickcheck-classes-base`. I'll release a new version of both later today. I'm running a build script right now to make sure everything still builds on old GHCs.

**Comment by andrewthad** [comment]
I've pushed some changes to `master` in anticipation of a release. Could you confirm that everything you're looking for is there? Then, I will release the new versions.

**Comment by Bodigrim** [comment]
Looks good, please go ahead. Thanks.

**Pull request merged**
