### PR TITLE
add ringLaws

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by skeuchel** [comment]
LGTM, but still compiling..

**Comment by chessai** [comment]
HEAD has been failing and i don't know why. But i expected that failure.

**Comment by chessai** [comment]
I think the HEAD is actually a development version pre-8.6 for some reason. The version there is 8.5.x

**Comment by andrewthad** [comment]
this looks good to me

**Comment by chessai** [comment]
i'm fairly confident that the head failure is unrelated

**Comment by skeuchel** [comment]
Oh sorry, yes I didn't want to imply that this PR makes head fail. The build of a dependency failed due to changes to template-haskell-2.15 that comes with hvr's ghc-8.7.20181217. So yes, it's unrelated.

**Comment by chessai** [comment]
oh, no i didn't think you were. i did think though that you might've been hesitant to merge if there was a failure, i only made that comment to say 'i think it's okay to merge'. interestingly enough the head failure is with hvr's stuff and nixpkgs head.

**Pull request merged**
