### PR TITLE
Compilation fixes and support for older QuickChecks

### PR DESCRIPTION
**Pull request by skeuchel**

### CODE REVIEW

**Comment by skeuchel** [comment]
Just noticed that it does not compile with GHC-8.6.1. Will fix this tomorrow.

**Comment by andrewthad** [comment]
Awesome. Thanks for doing this. Also, do you happen to be at ICFP?

**Comment by chessai** [comment]
If you are at ICFP it would be nice to meet you.

**Comment by skeuchel** [comment]
No, unfortunately, I had a conflict this year. See you maybe next year.

**Comment by skeuchel** [comment]
Ok, it builds for me now.

**Comment by chessai** [comment]
> @chessai Indeed, map coerce would be better, but I wouldn't change it here, since
   it's in the test suite
   only concerns legacy QuickChecks
   Data.Coerce is GHC>=7.8, so it would need more CPP

i agree with this

**Comment by chessai** [comment]
Tested this, it builds with ghc 861 and previous GHCs. Thanks very much!

**Pull request merged**
