### PR TITLE
Factor out quickcheck-classes-base

### PR DESCRIPTION
**Pull request by andrewthad**
@chessai Let me know if anything looks foul in here. I'm planning on releasing this later today.

### CODE REVIEW

**Comment by chessai** [comment]
So, Compat and Common are Internal right? But we have to export them from the -base package because the other library depends on it too. We need to mark those as internal and make clear that they aren't subject to PVP

**Comment by andrewthad** [comment]
They had already been marked as internal in the haddocks, but the `Internal` module naming convention is an additional useful way to communicate this, so I've consolidated them into a single module named `Test.QuickCheck.Classes.Internal`. This should make the intent even more clear.

**Comment by chessai** [comment]
Can you now use quickcheck-classes and notice no difference?

**Comment by andrewthad** [comment]
Build script still works with all old GHCs. Merging.

**Pull request merged**
