### PR TITLE
special semigroup laws

### PR DESCRIPTION
**Pull request by andrewthad**
resolves https://github.com/andrewthad/quickcheck-classes/issues/63

### CODE REVIEW

**Comment by chessai** [comment]
I am not sure i'm a fan of an extension to the API in this way - why would these not just be functions in the same way that all others are? `Proxy a -> Laws`? Instead of providing the user this datatype for marginal convenience. IMO this sort of datatype might be useful internally. Maybe I'm overblowing the extension. Feel free to explain why you might disagree, I'm not totally opposed to adding this.

**Comment by andrewthad** [comment]
That would probably be fine as well. I'll think on it more. We probably wouldn't want to have each of them repeatedly test the standard semigroup laws. So, if we go that route, we should change `commutativeSemigroup` to only test commutativity.

**Comment by andrewthad** [comment]
After thinking about this more, I agree with you. I've pushed a commit that changed to the scheme you recommended. Let me know if this looks good.

**Comment by chessai** [comment]
Yeah looks good. Does it build with ./build?

**Comment by andrewthad** [comment]
After waiting many moons, it does. Merging.

**Pull request merged**
