### PR TITLE
Euclidean and GcdDomain laws

### PR DESCRIPTION
**Pull request by Bodigrim**
This PR adds laws correspondent to recent developments in `semirings`: https://github.com/chessai/semirings/pull/39 and https://github.com/chessai/semirings/pull/46. 

It makes sense to keep this PR on hold until these changes are released on Hackage.

### CODE REVIEW

**Comment by chessai** [comment]
semirings-0.4.2 released.

**Comment by Bodigrim** [comment]
Thanks! I added CPP to retain compatibility with previous releases of `semirings`. The PR is ready for review.

**Comment by Bodigrim** [comment]
Any feedback please?

**Comment by chessai** [comment]
Sorry for the delay. This looks good mostly. Instead of "the several laws", could you add what those laws are in the haddocks? I believe semiringLaws (and most others) will have examples.

**Comment by chessai** [comment]
Also, if semringLaws could add that it tests the fromNatural laws

**Comment by chessai** [comment]
I think if you make those changes, along with a changelog entry, then this will be good

**Comment by Bodigrim** [comment]
Done, please take a look again.

**Comment by chessai** [comment]
Looks great! Merging.

**Pull request merged**
