### PR TITLE
semiringLaws: import Prelude.fromInteger qualified

### PR DESCRIPTION
**Pull request by Bodigrim**
To reflect latest changes in https://github.com/chessai/semirings/pull/48

### CODE REVIEW

**Comment by Bodigrim** [comment]
Those changes has been released in `semirings-0.5` and cause build failures for `quickcheck-classes`.

**Comment by chessai** [comment]
I thought I fixed this in

**Comment by Bodigrim** [comment]
Yep, 62d6e3a should be fine as well. Could you please also revise `quickcheck-classes-0.6.3.0` on Hackage, putting `semirings: >= 0.4.2 && < 0.5`?

**Comment by chessai** [comment]
revision made in http://hackage.haskell.org/package/quickcheck-classes-0.6.3.0/revisions/

**Pull request closed without merging**
