### PR TITLE
total ordering checking

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by andrewthad** [comment]
Looks good to me. Thanks!

**Comment by andrewthad** [comment]
I had to revert the definition of transitivity for ordering that this PR provides. It turned out to be incorrect.

**Comment by chessai** [comment]
How exactly was it incorrect?

**Comment by andrewthad** [comment]
Defined as:

    ordTransitive :: forall a. (Show a, Ord a, Arbitrary a) => Proxy a -> Property
    ordTransitive _ = property $ \(a :: a) b c -> ((a <= b) && (b <= c)) == (a <= c)

Consider testing the `Ord` instance for integers and assigning the variables as:

- a: 0
- b: 1
- c: 0

The property fails.

**Comment by chessai** [comment]
This is what it should test:
A > B and B > C, then also A > C|| A ≥ B and B ≥ C, then also A ≥ C|| A = B
and B = C, then also A = C

**Pull request merged**
