### PR TITLE
Use Num instances for Product and Sum from base-orphans for old GHCs

### LINKED ISSUE #68: master does not pass ./build
I did this.

We might need to incur a dependency on base-orphans.

### PR DESCRIPTION
**Pull request by skeuchel**
This fixes #68.

### CODE REVIEW

**Comment by chessai** [comment]
Just letting you know, you have commit bit now, it might be easier/better to work off of andrewthad/quickcheck-classes.

**Comment by chessai** [comment]
i am making sure this builds with ./build

**Comment by chessai** [comment]
Thanks!

**Comment by skeuchel** [comment]
> Just letting you know, you have commit bit now, it might be easier/better to work off of andrewthad/quickcheck-classes.

Yeah I know. I'm just not used to commit against master in a collaborative project ;)

**Comment by andrewthad** [comment]
Yeah, definitely don't commit straight to master. But, if you push you're branches to this repo instead of a fork, it's easier for the other maintainers to modify them.

**Comment by skeuchel** [comment]
>  if you push you're branches to this repo instead of a fork, it's easier for the other maintainers to modify them.

Fair point. Will do.

**Pull request merged**
